
export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS"
export const FETCH_INGREDIENTS_FAILED = "SET_INGREDIENTS_FAILED"

export const PURCHASE_BURGER_SUCCCESS ="PURCHASE_BURGER_SUCCCESS"
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL"
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START"